//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClaseDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDLago_01Entities1 : DbContext
    {
        public BDLago_01Entities1()
            : base("name=BDLago_01Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Table_1> Table_1 { get; set; }
        public DbSet<tblArticulo> tblArticulo { get; set; }
        public DbSet<tblCategoria> tblCategoria { get; set; }
        public DbSet<tblDetFactura> tblDetFactura { get; set; }
        public DbSet<tblDetFacturaTMP> tblDetFacturaTMP { get; set; }
        public DbSet<tblEmpleado> tblEmpleado { get; set; }
        public DbSet<tblFactura> tblFactura { get; set; }
        public DbSet<tblProveedor> tblProveedor { get; set; }
        public DbSet<tblUsuario> tblUsuario { get; set; }
    }
}
