//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDetFacturaTMP
    {
        public int IDDetFacturaTMP { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<float> Subtotal { get; set; }
        public Nullable<float> Total { get; set; }
        public Nullable<int> IDArticulos { get; set; }
        public Nullable<int> IDFactura { get; set; }
        public Nullable<int> IDUsuario { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<float> PrecioVenta { get; set; }
        public Nullable<float> Descuento { get; set; }
        public string Garantia { get; set; }
        public string Username { get; set; }
    
        public virtual tblArticulo tblArticulo { get; set; }
    }
}
