//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProveedor
    {
        public int IDProveedor { get; set; }
        public string NombNegocio { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Correo { get; set; }
        public string Fax { get; set; }
        public string Municipio { get; set; }
        public string Departamento { get; set; }
        public string Imagen { get; set; }
        public Nullable<bool> Estado { get; set; }
    }
}
