//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUsuario
    {
        public tblUsuario()
        {
            this.tblDetFactura = new HashSet<tblDetFactura>();
        }
    
        public int IDUsuario { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Rol { get; set; }
        public string Imagen { get; set; }
        public int IDEmpleado { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual ICollection<tblDetFactura> tblDetFactura { get; set; }
        public virtual tblEmpleado tblEmpleado { get; set; }
    }
}
